//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TokarevKursovEntities : DbContext
    {

        private static TokarevKursovEntities _context;

        public static TokarevKursovEntities GetContext()
        {
            if (_context == null)
                _context = new TokarevKursovEntities();
            return _context;
        }

        public TokarevKursovEntities()
            : base("name=TokarevKursovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Вид_жилья> Вид_жилья { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Пансионаты> Пансионаты { get; set; }
        public virtual DbSet<Путевки> Путевки { get; set; }
        public virtual DbSet<Тур> Тур { get; set; }
        public virtual DbSet<Клиенты_Копия> Клиенты_Копия { get; set; }
    }
}
