//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public int Код_клиента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Серия_паспорта { get; set; }
        public string Номер_паспорта { get; set; }
        public string Выдан_паспорт { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Адрес { get; set; }
        public string Город { get; set; }
        public string Телефон { get; set; }
    }
}
