//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Путевки
    {
        public int Код_путевки { get; set; }
        public int Клиент { get; set; }
        public int Тур { get; set; }
        public int Пансионат { get; set; }
        public System.DateTime Дата_заезда { get; set; }
        public System.DateTime Дата_отьезда { get; set; }
        public string Дети { get; set; }
        public string Мед_страховка { get; set; }
        public Nullable<int> Кол_во_человек { get; set; }
        public Nullable<decimal> Сумма { get; set; }
    
        public virtual Пансионаты Пансионаты { get; set; }
        public virtual Тур Тур1 { get; set; }
    }
}
