//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тур
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тур()
        {
            this.Путевки = new HashSet<Путевки>();
        }
    
        public int Код_тура { get; set; }
        public string Название { get; set; }
        public string Вид_транспорта { get; set; }
        public int Вид_жилья { get; set; }
        public string Вид_питания { get; set; }
        public decimal Цена_за_сутки { get; set; }
        public string Photo { get; set; }
        public string Вид_жилья1 { get; set; }
    
        public virtual Вид_жилья Вид_жилья2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Путевки> Путевки { get; set; }
    }
}
